In [5]:
import pandas as pd
import numpy as np
import os

In [10]:
os.chdir('C:/Users/user/Desktop/Classification/Ann/DecisionTree/')

In [11]:
data= pd.read_csv('zoo.csv')
data.head()

Animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   type  
0     1  
1     1  
2     4  
3     1  
4     1

In [12]:
data=data.drop('Animal_name',axis=1)
data.head()

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  backbone  \
0     1         0     0     1         0        0         1        1         1   
1     1         0     0     1         0        0         0        1         1   
2     0         0     1     0         0        1         1        1         1   
3     1         0     0     1         0        0         1        1         1   
4     1         0     0     1         0        0         1        1         1   

   breathes  venomous  fins  legs  tail  domestic  catsize  type  
0         1         0     0     4     0         0        1     1  
1         1         0     0     4     1         0        1     1  
2         0         0     1     0     1         0        0     4  
3         1         0     0     4     0         0        1     1  
4         1         0     0     4     1         0        1     1

In [22]:
X= data.iloc[:,: -1].values # remove the last variable alone
X = pd.DataFrame(X)
X.head()

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
0   1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1
1   1   0   0   1   0   0   0   1   1   1   0   0   4   1   0   1
2   0   0   1   0   0   1   1   1   1   0   0   1   0   1   0   0
3   1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1
4   1   0   0   1   0   0   1   1   1   1   0   0   4   1   0   1

In [25]:
y= data.iloc[:,16].values # get all the first 4 features / input variable in a variable y
y = pd.DataFrame(y)
y.head()

0
0  1
1  1
2  4
3  1
4  1

In [26]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [29]:
#train the model
tree = DecisionTreeClassifier(criterion = 'entropy').fit(X_train,y_train)

In [30]:
#predict the model
prediction = tree.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

In [36]:
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, prediction)) 

Accuracy :  0.9615384615384616


In [38]:
print(classification_report(y_test, prediction) )

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         5
           3       0.50      1.00      0.67         1
           4       1.00      1.00      1.00         5
           5       0.00      0.00      0.00         1
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         2

    accuracy                           0.96        26
   macro avg       0.79      0.86      0.81        26
weighted avg       0.94      0.96      0.95        26



C:\Users\user\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [39]:
cm = confusion_matrix(y_test, prediction) 
  
print ("Confusion Matrix : \n", cm) 

Confusion Matrix : 
 [[10  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0]
 [ 0  0  1  0  0  0  0]
 [ 0  0  0  5  0  0  0]
 [ 0  0  1  0  0  0  0]
 [ 0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  2]]
